[package]
name = "OptionContracts"
version = "0.0.1"

[addresses]
# Allow override at publish time
Apex = "_"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "aptos-node-v1.14.4", subdir = "aptos-move/framework/move-stdlib" }


